### ISSUE TITLE
How can I use old function? ( openwrt-install / openwrt-update )

### ISSUE THREAD

**Issue by kousyougi** [ophub/op#16]
I compiled simplest openwrt which is without LUCI.
How can I use the old function like "openwrt-install" and "openwrt-update"

Thanks

**Comment by ophub** [comment]
The previous commands can be used, such as
```
Installation: openwrt-install
Update: openwrt-update
Backup: openwrt-backup
```

Luci also works through these commands. Both command and luci can be used, you can choose the way you like.
