### ISSUE TITLE
大神，能支持x96 max+的wifi开启吗

### ISSUE THREAD

**Issue by underlaw** [ophub/op#5]
大神，
1、能支持x96 max+的wifi开启吗，
2、还有一个 外接usb网卡当wan口, 在usb3时 wan口几秒钟就掉一次，在usb2接口时很稳。。。这原因是：电源问题 还是盒子质量问题 还是固件问题了
3、能把这前面的灯点亮吗，比如开机后

**Comment by ophub** [comment]
1. Currently, the network card driver does not support it, only when there is a suitable driver.
2. The original power supply will be insufficient when used in China, please use a power supply not less than 5V3A+.
3. LED lights are not currently supported

**Comment by underlaw** [comment]
thx
