### ISSUE TITLE
Add passwall plugin?

### ISSUE THREAD

**Issue by happy201807** [ophub/op#7]
Hi,could you add the project https://github.com/xiaorouji/openwrt-passwall，the plugin has built-in DOH and chinadns-ng improve to resolve dns pollution. Could you add support?

**Comment by ophub** [comment]
You can add a personalized plug-in package in the corresponding router firmware configuration file, take x86_64 as an example:
https://github.com/ophub/op/tree/main/router/x86_64

1. Add the package repository address in diy-part2.sh. [ Refer to the 19 line of code. ]
2. Add the package name in the .config file. [ Refer to the 225 line of code. ]
3. Run the compiled script in Actions to complete the customized openwrt
4. Download the compiled openwrt installation file in Actions or Release
