### ISSUE TITLE
openwrt_s905x3_v5.4.124_2021.06.08.0613.img.gz 安装出现错误

### ISSUE THREAD

**Issue by kousyougi** [ophub/op#8]
openwrt_s905x3_v5.4.124_2021.06.08.0613.img.gz 用openwrt-install出现错误，安装不上去。
错误信息跟分区有关。

5.4.123 板没有问题。

**Comment by ophub** [comment]
![Snip20210609_1](https://user-images.githubusercontent.com/68696949/121275508-77f9b000-c8ff-11eb-8864-00135a5ce7e5.png)

![Snip20210609_2](https://user-images.githubusercontent.com/68696949/121275520-7f20be00-c8ff-11eb-8ef6-5d881ba22239.png)

![Snip20210609_3](https://user-images.githubusercontent.com/68696949/121275527-834cdb80-c8ff-11eb-9465-bc8fd29e3f89.png)

![Snip20210609_4](https://user-images.githubusercontent.com/68696949/121275530-8647cc00-c8ff-11eb-8f2e-459978ce1a00.png)

I tested it and it can be installed correctly. You can restart the device and try again.

**Comment by ophub** [comment]
![Snip20210609_5](https://user-images.githubusercontent.com/68696949/121275891-2f8ec200-c900-11eb-828a-6016b76ef23d.png)

The firmware provides luci support and can be used in the panel. The result of luci-app-amlogic is the same as the command operation.

**Comment by kousyougi** [comment]
刚刚测，出现下面错误信息
![hk1box](https://user-images.githubusercontent.com/43228565/121293331-09781a80-c91e-11eb-96c8-488515fca26b.jpg)

是hk1box的机子，我自己电脑里面有留openwrt_s905x3_v5.4.123_2021.06.07.0514.img.gz
还原/lib/u-boot/hk1box-bootloader.img 重新启动刷v5.4.123可以正常openwrt-install

同样的步骤，刷openwrt_s905x3_v5.4.124_2021.06.09.0505.img 执行openwrt-install就出现错误。

**Comment by kousyougi** [comment]
成功了。
我又再洗一次/lib/u-boot/hk1box-bootloader.img，然后再执行openwrt-install就成功了。
谢谢
